### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by ghost** [bretth/woven#17]
woven should also support Debian

**Comment by bretth** [comment]
please advise what output a debian host gives with: cat /etc/issue 

I can make changes that would make it nominally run on debian, but since I don't use debian someone would need to confirm it works. Once the api matures a bit I will look at a CI strategy for testing against different distributions, probably once I add libcloud support.

**Comment by ghost** [comment]
Hi,
thanks for going forward on this. I reckon if woven also supports Debian it will get a lot more folks being interested.

cat /etc/issue is deprecated. These days you use cat /etc/debian_version

http://www.markus-gattol.name/ws/debian_notes_cheat_sheets.html#debian_release_version

So if it exists, you know it's Debian. The release (e.g. lenny) is also given.

I can then of course test if it works since I am a 100% Debian user.

**Comment by bretth** [comment]
I've renamed the ubuntu module to linux and refactored it a little bit to make the functions not distribution specific. I've added in a function lsb_release to pick up the distro info (thanks for the pointer). From here on in I will have to depend on user reports, and fix specific issues if they come up. Thanks.
