### ISSUE TITLE
unify pip related data under .pip root directory

### ISSUE THREAD

**Issue by ghost** [bretth/woven#21]
Under conventions with regards to filesystem layout [0] we have basically three pip related directories at the siteroot
- ~/.package_cache
  - ~/.pip
  - ~/src

I'd suggest to unify this into
- ~/.pip/pip.log (a file)
- ~/.pip/cache  (a dir)
- ~/.pip/source (a dir)
- ~/.pip/build (a dir)

[1] gives a good idea about it.
- [0] https://github.com/bretth/woven/blob/master/docs/conventions.rst
- [1] http://www.markus-gattol.name/ws/python.html#pip_settings_in_bashrc

**Comment by bretth** [comment]
Thanks for the suggestion. I have moved src and cache to be under .pip. I'm ambivalent about specifying build since it is effectively a tmp directory for pip, and I currently let pip decide where to put and destroy it. The others obviously come into play when creating new envs. 

I split out pip.log because it's a bit quicker to diagnose installation issues relating to particular packages in a given requirements file. I can't remember what triggered me to make that decision, but I do remember it involved wading through crap in pip logs. This just allows you to break it out a bit if there are a lot of packages.
