### ISSUE TITLE
Support using Windows for development/source of deployment

### ISSUE THREAD

**Issue by mortenlj** [bretth/woven#27]
Many people (myself included), do development on a windows machine. While I understand that supporting windows on the server would be complicated and probably not worth it, it would be very beneficial if it would atleast be possible to use windows as a platform for development / source of deployment.

I haven't been digging too deeply into Woven, but if the only reason for this limitation is that Woven uses rsync, I would imagine there are other solutions available that would work equally well on windows.

**Comment by shockflash** [comment]
"is that Woven uses rsync"

I used rsync von windows 10 years ago, should be still possible today. You can use cygwin rsync oder native binaries for windows. 
I don't now which binaries are good today, since I don't use any windows systems for development anymore. 

Another way of solving this issue is to use a virtual linux in Virtualbox, Vmware or anything like that. Only for woven deploy, or for full working (via samba/nfs share) on this system. Without a database server (or a small database), less then 128 MB RAM are needed for such an system.

**Comment by mortenlj** [comment]
Closing old issues that don't matter to me anymore, and that doesn't seem to have any traction/interest.
